# Generated by Django 4.2.30 on 2026-07-16 06:41

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_book_title_trgm_idx_person_person_name_trgm_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='books.book'),
        ),
        migrations.AddIndex(
            model_name='bookshelf',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='bookshelf_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='subject_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text'], name='summary_text_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
