"""
Django settings for gutendex project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import dj_database_url
import environ
import os


# Import environment variables
env = environ.Env(
    ADMIN_EMAILS=(list, []),
    ADMIN_NAMES=(list, []),
    ALLOWED_HOSTS=(list, []),
    DEBUG=(bool, False),
    MANAGER_EMAILS=(list, []),
    MANAGER_NAMES=(list, []),
)
env_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), '.env')
if os.path.isfile(env_file):
    environ.Env.read_env(env_file)


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')
API_KEY = env('API_KEY', default=None)



# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Other third-party apps
    'corsheaders',
    'rest_framework',

    # Project apps
    'books',
]

MIDDLEWARE = [
    'gutendex.middleware.JsonExceptionMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'gutendex.middleware.ApiKeyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gutendex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'gutendex/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gutendex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DATABASE_NAME', default='gutendex'),
        'USER': env('DATABASE_USER', default=''),
        'PASSWORD': env('DATABASE_PASSWORD', default=''),
        'HOST': env('DATABASE_HOST', default='127.0.0.1'),
        'PORT': env('DATABASE_PORT', default='5432'),
    }
}

# Heroku injects DATABASE_URL — override the above when present
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        ssl_require=True
    )

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = env('STATIC_ROOT', default=os.path.join(BASE_DIR, 'staticfiles'))
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# User-uploaded files
MEDIA_ROOT = env('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'media'))
MEDIA_URL = '/media/'


# Users for error reporting
ADMIN_EMAILS = env('ADMIN_EMAILS')
ADMIN_NAMES = env('ADMIN_NAMES')
ADMIN_COUNT = len(ADMIN_EMAILS)
ADMINS = [
    (ADMIN_NAMES[i], ADMIN_EMAILS[i]) for i in range(ADMIN_COUNT)
]
MANAGER_EMAILS = env('MANAGER_EMAILS')
MANAGER_NAMES = env('MANAGER_NAMES')
MANAGER_COUNT = len(MANAGER_EMAILS)
MANAGERS = [
    (MANAGER_NAMES[i], MANAGER_EMAILS[i]) for i in range(MANAGER_COUNT)
]


# Email
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_HOST_ADDRESS = env('EMAIL_HOST_ADDRESS', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')


# Directory paths for catalog files and updater
BASE_CATALOG_DIR = os.path.join(BASE_DIR, 'catalog_files')
CATALOG_RDF_DIR = os.path.join(BASE_CATALOG_DIR, 'rdf')
CATALOG_INDEX_DIR = os.path.join(CATALOG_RDF_DIR, 'index.json')
CATALOG_LOG_DIR = os.path.join(BASE_CATALOG_DIR, 'log')
CATALOG_TEMP_DIR = os.path.join(BASE_CATALOG_DIR, 'tmp')


# Settings for Django REST Framework JSON API
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': env('THROTTLE_RATE_ANON', default='120/minute'),
    },
    'PAGE_SIZE': 32
}


# Cross-origin resource sharing with `corsheaders` middleware
CORS_ALLOW_ALL_ORIGINS = True


# S3-compatible object storage for cached book content
# Works with AWS S3, Heroku Bucketeer, DigitalOcean Spaces
S3_BUCKET_NAME = env('S3_BUCKET_NAME', default=env('BUCKETEER_BUCKET_NAME', default=''))
S3_ACCESS_KEY_ID = env('S3_ACCESS_KEY_ID', default=env('BUCKETEER_AWS_ACCESS_KEY_ID', default=''))
S3_SECRET_ACCESS_KEY = env('S3_SECRET_ACCESS_KEY', default=env('BUCKETEER_AWS_SECRET_ACCESS_KEY', default=''))
S3_ENDPOINT_URL = env('S3_ENDPOINT_URL', default='')  # e.g. https://s3.amazonaws.com
S3_REGION = env('S3_REGION', default=env('BUCKETEER_AWS_REGION', default='us-east-1'))
S3_CUSTOM_DOMAIN = env('S3_CUSTOM_DOMAIN', default='')  # CDN/public URL prefix if different from endpoint


# Project Gutenberg mirrors — NEVER fetch from www.gutenberg.org directly
# Override via config var as comma-separated list
_raw_mirrors = env(
    'GUTENBERG_MIRRORS',
    default='https://www.gutenberg.org/cache/epub,https://gutenberg.pglaf.org/cache/epub'
)
GUTENBERG_MIRRORS = [m.strip() for m in _raw_mirrors.split(',') if m.strip()]


# Worker settings
CONTENT_WORKER_POLL_INTERVAL = int(env('CONTENT_WORKER_POLL_INTERVAL', default='5'))  # seconds
CONTENT_FETCH_TIMEOUT = int(env('CONTENT_FETCH_TIMEOUT', default='120'))  # seconds per mirror attempt


# Production Security Controls (Active when running in non-debug mode)
if not DEBUG:
    # Tell Django that we are behind Heroku's SSL reverse proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    
    # Secure Session and CSRF cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HTTP Strict Transport Security (HSTS) headers (1 year duration)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Logging configuration (required for proper monitoring via heroku logs)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s',
            'datefmt': '%d/%b/%Y %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'books': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


